### ISSUE TITLE
Update removed styles from tmux 2.9

### ISSUE THREAD

**Issue by anchnk** [challenger-deep-theme/tmux#1]
According to the [tmux FAQ](https://github.com/tmux/tmux/wiki/FAQ#how-do-i-translate--fg--bg-and--attr-options-into--style-options), styling options that were used before tmux 1.9 (i.e `mode-fg`, `mode-bg` and `mode-attr`) are removed from the tmux 2.9. 

Instead styling should be done by the x-style option that combines all options in one.

With the current configuration, tmux reports invalid options. The configuration must be updated to match the style option.

**Comment by MaxSt** [comment]
Thank you! :+1:
